In [2]:
import numpy as np

In [2]:
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distributor_init',
 '_financi

In [1]:
my_list = [1,2,3,4]

In [3]:
my_arr = np.array(my_list)

In [4]:
type(my_arr)

numpy.ndarray

In [5]:
l2 = [11,22,33,44]

In [6]:
my_arr2 = np.array([my_list,l2])

In [9]:
my_arr2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [7]:
l3 = ['ram','shyam','sia']

In [8]:
arr_names = np.array(l3)

In [9]:
arr_names

array(['ram', 'shyam', 'sia'], dtype='<U5')

In [10]:
l4 = ['100',23.45,'john']

In [11]:
arr_l4 = np.array(l4)

In [12]:
arr_l4

array(['100', '23.45', 'john'], dtype='<U32')

In [16]:
l5 = [(100,23.45,'john'),(200,25.95,'Smith')]

In [17]:
arr_l5 = np.array(l5)

In [18]:
arr_l5

array([['100', '23.45', 'john'],
       ['200', '25.95', 'Smith']], dtype='<U32')

In [13]:
#shape
my_arr.shape

(4,)

In [14]:
my_arr2.shape

(2, 4)

In [21]:
arr_l5.shape

(2, 3)

In [15]:
#dtype
my_arr.dtype

dtype('int32')

In [23]:
arr_l5.dtype

dtype('<U32')

In [30]:
newlist = [11,22,33,55]

In [31]:
my_list

[1, 2, 3, 4]

In [39]:
arr_newlist= np.array([newlist,my_list,l2])

In [34]:
arr_newlist.dtype

dtype('int32')

In [37]:
arr_newlist.shape

(3, 4)

In [41]:
arr_newlist

array([[11, 22, 33, 55],
       [ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [16]:
#array with zeros
arr_zeros= np.zeros(5)

In [43]:
arr_zeros

array([0., 0., 0., 0., 0.])

In [44]:
arr_zeros.dtype

dtype('float64')

In [46]:
arr_2zeros = np.zeros([5,2])

In [47]:
arr_2zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [17]:
#ones
arr_ones = np.ones(5)

In [18]:
arr_ones

array([1., 1., 1., 1., 1.])

In [50]:
arr_ones.dtype

dtype('float64')

In [19]:
arr_2ones = np.ones([2,9])

In [53]:
arr_2ones

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [20]:
#empty array
arr_empty = np.empty(5)

In [55]:
arr_empty.dtype

dtype('float64')

In [21]:
arr_empty

array([1., 1., 1., 1., 1.])

In [22]:
#generate the identity matrix
arr_id = np.eye(5)

In [58]:
arr_id.dtype

dtype('float64')

In [23]:
arr_id

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
#arange to generate the arr
arr_rng = np.arange(5)

In [27]:
arr_rng

array([0, 1, 2, 3, 4])

In [31]:
arr2d = np.arange(50)

## 

In [26]:
arr2d

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

In [34]:
new2d=arr2d.reshape(5,10)

In [35]:
arr2d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [36]:
new2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [37]:
arr2d[1]

1

In [38]:
arr2d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [39]:
arr_l4

array(['100', '23.45', 'john'], dtype='<U32')

In [41]:
arr_l4[0]

'100'

In [42]:
arr_l4[2]

'john'

In [43]:
arr_l4[3]

<class 'IndexError'>: index 3 is out of bounds for axis 0 with size 3

In [44]:
new2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [45]:
new2d[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
new2d[0][1]

1

In [47]:
new2d[1:]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [48]:
new2d[:2]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [53]:
new2d[1][:2]

array([10, 11])

In [54]:
new2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [59]:
new2d[3][1:3]

array([31, 32])

In [60]:
new2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [61]:
new2dT = new2d.T

In [62]:
new2dT

array([[ 0, 10, 20, 30, 40],
       [ 1, 11, 21, 31, 41],
       [ 2, 12, 22, 32, 42],
       [ 3, 13, 23, 33, 43],
       [ 4, 14, 24, 34, 44],
       [ 5, 15, 25, 35, 45],
       [ 6, 16, 26, 36, 46],
       [ 7, 17, 27, 37, 47],
       [ 8, 18, 28, 38, 48],
       [ 9, 19, 29, 39, 49]])

In [63]:
new2d.shape

(5, 10)

In [65]:
new2dT.shape

(10, 5)

In [66]:
arr2d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [67]:
arr2d.sum()

1225

In [68]:
new2d.sum()

1225

In [69]:
new2d.sum(axis=0)

array([100, 105, 110, 115, 120, 125, 130, 135, 140, 145])

In [70]:
new2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [71]:
new2d.sum(axis=1)

array([ 45, 145, 245, 345, 445])

In [72]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [109]:
arOfX = np.array(x)

In [75]:
arOfX.shape

(3, 3)

In [76]:
arOfX

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [77]:
arOfX.sum()

29

In [78]:
arOfX.sum(axis=0)     # columwise

array([12,  8,  9])

In [79]:
arOfX.sum(axis=1)    # rowwise

array([ 6, 15,  8])

In [80]:
arOfX.std()

2.2986845406196887

In [81]:
arOfX.sort()

In [82]:
arOfX

array([[1, 2, 3],
       [4, 5, 6],
       [0, 1, 7]])

In [83]:
arOfX.sort(axis=0)

In [84]:
arOfX

array([[0, 1, 3],
       [1, 2, 6],
       [4, 5, 7]])

In [85]:
arOfX.sort(axis=0)

In [86]:
arOfX

array([[0, 1, 3],
       [1, 2, 6],
       [4, 5, 7]])

In [87]:
arr2d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [88]:
arr2d.size

50

In [89]:
arOfX.size

9

In [90]:
arr_ones

array([1., 1., 1., 1., 1.])

In [91]:
arr_ones.dtype

dtype('float64')

In [92]:
arr_ones_new = arr_ones.astype(int)

In [93]:
arr_ones_new

array([1, 1, 1, 1, 1])

In [94]:
# casting
arr_ones_new.dtype

dtype('int32')

In [96]:
new2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [97]:
flatten_new2d = new2d.ravel()

In [98]:
new2d.shape

(5, 10)

In [99]:
flatten_new2d.shape

(50,)

In [100]:
flatten_new2d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [102]:
flat_new2d = new2d.flat

In [104]:
flat_new2d

In [105]:
for i in flat_new2d:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49


In [106]:
flatten_new2d.ndim

1

In [107]:
new2d.ndim

2

In [108]:
new2d.shape

(5, 10)

In [110]:
arOfX

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [111]:
my_arr

array([1, 2, 3, 4])

In [112]:
my_arr.argmin()                   # index 

0

In [113]:
my_arr.min()                     # value

1

In [114]:
my_arr.argmax()

3

In [115]:
my_arr.max()

4

In [116]:
arOfX.min()

0

In [117]:
arOfX

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [118]:
arOfX.argmin()

8

In [119]:
arOfX.argmin(axis=0)

array([0, 2, 2], dtype=int32)

In [120]:
new2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [121]:
new2d.argmin()

0

In [122]:
new2d.argmin(axis=0)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [123]:
arOfX

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [124]:
arOfX.argmin(axis=1)

array([0, 0, 2], dtype=int32)

In [125]:
arOfX.min(axis=1)

array([1, 4, 0])

In [126]:
arOfX.min()

0

In [127]:
arOfX.min(axis=0)

array([1, 1, 0])

In [128]:
arOfX.argmin(axis=0)

array([0, 2, 2], dtype=int32)

In [129]:
my_arr.var()

1.25

In [130]:
arOfX.var()

5.28395061728395

In [131]:
arOfX.var(axis=1)

array([0.66666667, 0.66666667, 9.55555556])

In [132]:
my_arr

array([1, 2, 3, 4])

In [133]:
np.sqrt(my_arr)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [134]:
np.sort(arOfX)

array([[1, 2, 3],
       [4, 5, 6],
       [0, 1, 7]])

In [135]:
import random

In [136]:
A= np.random.rand(10)

In [137]:
A

array([0.6667369 , 0.13806132, 0.06023156, 0.64629878, 0.15592128,
       0.78353179, 0.73893201, 0.46051159, 0.77498659, 0.50416893])

In [138]:
B= np.random.rand(10)

In [139]:
B

array([0.7546086 , 0.42394168, 0.49801666, 0.41973904, 0.31669083,
       0.88924899, 0.90034041, 0.4048026 , 0.4396504 , 0.0510894 ])

In [140]:
A+B

array([1.42134551, 0.562003  , 0.55824822, 1.06603782, 0.47261212,
       1.67278079, 1.63927242, 0.86531419, 1.21463699, 0.55525834])

In [141]:
A-B

array([-0.0878717 , -0.28588035, -0.4377851 ,  0.22655974, -0.16076955,
       -0.1057172 , -0.1614084 ,  0.05570898,  0.33533619,  0.45307953])

In [142]:
my_arr

array([1, 2, 3, 4])

In [143]:
1/my_arr

array([1.        , 0.5       , 0.33333333, 0.25      ])

In [149]:
C = np.random.randint(10)

In [150]:
C

0

In [151]:
A_Int = A.astype(int)

In [152]:
A_Int

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [156]:
my_arr * my_arr

array([ 1,  4,  9, 16])

In [157]:
my_arr **3

array([ 1,  8, 27, 64], dtype=int32)

In [158]:
np.add(A,B)

array([1.42134551, 0.562003  , 0.55824822, 1.06603782, 0.47261212,
       1.67278079, 1.63927242, 0.86531419, 1.21463699, 0.55525834])

In [159]:
A+B

array([1.42134551, 0.562003  , 0.55824822, 1.06603782, 0.47261212,
       1.67278079, 1.63927242, 0.86531419, 1.21463699, 0.55525834])

In [160]:
A

array([0.6667369 , 0.13806132, 0.06023156, 0.64629878, 0.15592128,
       0.78353179, 0.73893201, 0.46051159, 0.77498659, 0.50416893])

In [161]:
A[:5]

array([0.6667369 , 0.13806132, 0.06023156, 0.64629878, 0.15592128])

In [162]:
A

array([0.6667369 , 0.13806132, 0.06023156, 0.64629878, 0.15592128,
       0.78353179, 0.73893201, 0.46051159, 0.77498659, 0.50416893])

In [163]:
copy_A= A[:5]

In [164]:
A[:5] =99

In [165]:
A

array([99.        , 99.        , 99.        , 99.        , 99.        ,
        0.78353179,  0.73893201,  0.46051159,  0.77498659,  0.50416893])

In [166]:
new2d[:2,:1]

array([[ 0],
       [10]])

In [167]:
new2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [168]:
new2d[:2,:1] = 99

In [169]:
new2d

array([[99,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [99, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [172]:
new2d[:2,:2]

array([[99,  1],
       [99, 11]])

In [173]:
new2d[:3,:3]

array([[99,  1,  2],
       [99, 11, 12],
       [20, 21, 22]])

In [174]:
arOfX

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [175]:
my_arr

array([1, 2, 3, 4])

In [176]:
np.where(my_arr<3)

(array([0, 1], dtype=int32),)

In [177]:
np.where(arOfX <3)

(array([0, 0, 2, 2], dtype=int32), array([0, 1, 1, 2], dtype=int32))

In [178]:
np.where(arOfX>5)

(array([1, 2], dtype=int32), array([2, 0], dtype=int32))

In [180]:
np.where(arOfX >3)

(array([1, 1, 1, 2], dtype=int32), array([0, 1, 2, 0], dtype=int32))

In [181]:
my_arr

array([1, 2, 3, 4])

In [183]:
np.save('my_arr',my_arr)

In [184]:
read_arr = np.load('my_arr.npy')

In [185]:
read_arr

array([1, 2, 3, 4])

In [187]:
np.savetxt('my_arr2.txt',my_arr)

In [188]:
read_arr2 = np.loadtxt('my_arr2.txt')

In [189]:
read_arr2

array([1., 2., 3., 4.])

In [195]:
ppl = np.loadtxt('purplecow.txt',dtype='str')

In [196]:
ppl

array([["I've", 'never', 'seen', 'a', 'purple', 'cow.'],
       ['I', 'never', 'hope', 'to', 'see', 'one;'],
       ['But', 'I', 'can', 'tell', 'you,', 'anyhow,'],
       ["I'd", 'rather', 'see', 'than', 'be', 'one.']], dtype='<U7')

In [197]:
A

array([99.        , 99.        , 99.        , 99.        , 99.        ,
        0.78353179,  0.73893201,  0.46051159,  0.77498659,  0.50416893])

In [198]:
B

array([0.7546086 , 0.42394168, 0.49801666, 0.41973904, 0.31669083,
       0.88924899, 0.90034041, 0.4048026 , 0.4396504 , 0.0510894 ])

In [199]:
np.savez('multi',x=A,y=B)

In [201]:
data_multi = np.load('multi.npz')

In [202]:
data_multi

NpzFile 'multi.npz' with keys: x, y

In [204]:
data_multi['x']

array([99.        , 99.        , 99.        , 99.        , 99.        ,
        0.78353179,  0.73893201,  0.46051159,  0.77498659,  0.50416893])

In [205]:
data_multi['y']

array([0.7546086 , 0.42394168, 0.49801666, 0.41973904, 0.31669083,
       0.88924899, 0.90034041, 0.4048026 , 0.4396504 , 0.0510894 ])