In [ ]:
import logging
logging.basicConfig(filename='sept20.log',level=logging.DEBUG)

In [ ]:
logging.debug("hello")

In [ ]:
l1 = [1,2,3,45]

In [ ]:
next(l1.__iter__())

In [ ]:
itr1=iter(l1)

In [ ]:
type(itr1)

In [ ]:
next(itr1)

In [ ]:
dir(itr1)

In [ ]:
itr1.__next__()

In [8]:
import memory_profiler as mem_profile


In [13]:
memory_usage()

[22.9453125]

In [10]:
print('Memory (Before): ' + str(mem_profile.memory_usage()) + 'MB' )



Memory (Before): [91.75390625]MB


In [11]:
l1 = [12,3,4]

In [12]:
print('Memory (Before): ' + str(mem_profile.memory_usage()) + 'MB' )

Memory (Before): [91.76171875]MB


In [19]:
'this is india'.split()[1]

'is'

In [22]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [23]:
import numpy as np

In [24]:
arr = np.array(x)

In [25]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [26]:
arr.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [29]:
arr.sum(axis=1)

array([ 6, 15,  8])

In [44]:
np.where(arr>3,arr,0)

array([[0, 0, 0],
       [4, 5, 6],
       [7, 0, 0]])

In [37]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [51]:
np.where(arr>6)

(array([2], dtype=int64), array([0], dtype=int64))

In [55]:
np.count_nonzero(arr)

8

In [68]:
a1 = np.ones(5)

In [61]:
a1

array([1., 1., 1., 1., 1.])

In [70]:
a1.astype(int)

array([1, 1, 1, 1, 1])

In [71]:
import sys

In [72]:
l1 =[1,2,3,4,5,6,7]

In [73]:
arrl1 = np.array(l1)

In [75]:
sys.getsizeof(1)*len(arrl1)

196

In [79]:
arrl1.itemsize * arrl1.size

28

7

In [80]:
arr[0]

array([1, 2, 3])

In [81]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [82]:
arr[1]

array([4, 5, 6])

In [83]:
arr[2]

array([7, 1, 0])

In [84]:
arr[1][1]

5

In [85]:
arr[:1]

array([[1, 2, 3]])

In [86]:
arr[1:]

array([[4, 5, 6],
       [7, 1, 0]])

In [87]:
arr[1][:2]

array([4, 5])

In [91]:
import webbrowser
import pandas as pd

In [89]:
web= 'https://en.wikipedia.org/wiki/List_of_all-time_NFL_win%E2%80%93loss_records'

In [90]:
webbrowser.open(web)

True

In [92]:
nfl= pd.read_clipboard()

In [93]:
nfl

Rank                  Team     GP  Won  Lost Tied[c]   Pct.  \
0     1        Dallas Cowboys    981  562   413   6 (0)  0.576   
1     2     Green Bay Packers  1,435  800   598  38 (8)  0.572   
2     3      Baltimore Ravens    451  256   194       1  0.569   
3     4         Chicago Bears  1,469  793   634  42 (1)  0.556   
4     5  New England Patriots    983  541   433   9 (0)  0.555   
5     6        Miami Dolphins    899  496   399   4 (1)  0.554   
6     7    Kansas City Chiefs    983  532   439  12 (4)  0.548   

   First NFL season   Division  
0              1960   NFC East  
1              1921  NFC North  
2              1996  AFC North  
3              1920  NFC North  
4              1960   AFC East  
5              1966   AFC East  
6              1960   AFC West

In [99]:
nfl.iloc[:2]

Rank               Team     GP  Won  Lost Tied[c]   Pct.  First NFL season  \
0     1     Dallas Cowboys    981  562   413   6 (0)  0.576              1960   
1     2  Green Bay Packers  1,435  800   598  38 (8)  0.572              1921   

    Division  
0   NFC East  
1  NFC North

In [102]:
dataframe2 = pd.read_excel(r'C:\Users\Krishna\data\python\nfl.xlsx', sheet_name = "Sheet1")

In [103]:
dataframe2

Rank                    Team    GP  Won  Lost Tied[c]   Pct.  \
0      1          Dallas Cowboys   981  562   413   6 (0)  0.576   
1      2       Green Bay Packers  1435  800   598  38 (8)  0.572   
2      3        Baltimore Ravens   451  256   194       1  0.569   
3      4           Chicago Bears  1469  793   634  42 (1)  0.556   
4      5    New England Patriots   983  541   433   9 (0)  0.555   
5      6          Miami Dolphins   899  496   399   4 (1)  0.554   
6      7      Kansas City Chiefs   983  532   439  12 (4)  0.548   
7      8       Minnesota Vikings   969  523   435  11 (4)  0.546   
8      9  San Francisco 49ers[b]  1101  586   501  14 (3)  0.539   
9     10     Pittsburgh Steelers  1271  671   578  22 (4)  0.537   
10    11         New York Giants  1404  721   649  34 (4)  0.526   
11    12   Indianapolis Colts[d]  1065  556   501   8 (2)  0.526   
12    13          Denver Broncos   983  508   465  10 (4)  0.522   
13    14       Las Vegas Raiders   983  505   467  11 (2)  0.520   
14    15        Seattle Seahawks   759  392   366       1  0.517   
15    16        Los Angeles Rams  1234  614   599  21 (3)  0.506   
16    17    Los Angeles Chargers   983  483   489  11 (2)  0.497   
17    18     Philadelphia Eagles  1287  624   636  27 (7)  0.495   
18    19   Washington Commanders  1301  629   643  29 (3)  0.495   
19    20  Cleveland Browns[b][e]  1053  512   530  11 (4)  0.491   
20    21        Tennessee Titans   983  476   501   6 (0)  0.487   
21    22           Buffalo Bills   982  473   501   8 (1)  0.486   
22    23      New Orleans Saints   870  412   468   5 (1)  0.468   
23    24       Carolina Panthers   467  214   252       1  0.459   
24    25      Cincinnati Bengals   869  394   471   5 (4)  0.456   
25    26           Detroit Lions  1332  591   707  34 (5)  0.455   
26    27           New York Jets   983  428   547   8 (2)  0.439   
27    28         Atlanta Falcons   899  390   503   6 (2)  0.437   
28    29          Houston Texans   355  152   202       1  0.430   
29    30    Jacksonville Jaguars   467  198   269       0  0.424   
30    31       Arizona Cardinals  1429  585   803  41 (6)  0.422   
31    32    Tampa Bay Buccaneers   759  308   450       1  0.406   

    First NFL season   Division  
0               1960   NFC East  
1               1921  NFC North  
2               1996  AFC North  
3               1920  NFC North  
4               1960   AFC East  
5               1966   AFC East  
6               1960   AFC West  
7               1961  NFC North  
8               1950   NFC West  
9               1933  AFC North  
10              1925   NFC East  
11              1953  AFC South  
12              1960   AFC West  
13              1960   AFC West  
14              1976   NFC West  
15              1937   NFC West  
16              1960   AFC West  
17              1933   NFC East  
18              1932   NFC East  
19              1950  AFC North  
20              1960  AFC South  
21              1960   AFC East  
22              1967  NFC South  
23              1995  NFC South  
24              1968  AFC North  
25              1930  NFC North  
26              1960   AFC East  
27              1966  NFC South  
28              2002  AFC South  
29              1995  AFC South  
30              1920   NFC West  
31              1976  NFC South